#!/bin/bash

# Run the binary and capture the output
config_path=$(node-shell-init)

# Check if the output is a valid file path
if [[ -f "${config_path}" ]]; then
  echo "Sourcing configuration file: ${config_path}"

  # Start a new shell and source the configuration file within it
  bash --rcfile $config_path
else
  echo "Invalid configuration file path: ${config_path}"
fi
